### PR TITLE
License rebase

### PR DESCRIPTION
**Pull request by tacketar**

### CODE REVIEW

**Review by PerilousApricot — APPROVED** [review]
:+1:

**Comment by PerilousApricot** [comment]
Currently fails some tests because of missing berkleydb: https://jenkins.accre.vanderbilt.edu/blue/organizations/jenkins/LStore-Branches/detail/PR-153/2/pipeline/34

**Comment by tacketar** [comment]
What's the underlying distro?  It would be useful to add the misc 
package environments to the package.sh auto-build so we can test before 
the commit.  I've had a similar jenkins issue before.

**Comment by PerilousApricot** [comment]
Well, I think the problem is that changing the image messes up things
weirdly because the master branch and the PR both use the same docker image
names, so there's a race.I run 'generate-docker-image' in the branch, but
it looks like it's getting the one from the master branch still. I reran it
and it looks likeit clicked though.

**Pull request merged**
