### PR TITLE
Final version before deploying on cluster

### PR DESCRIPTION
**Pull request by tacketar**
This has all the fixes and issues resolved uncovered in the last month along with some notable features that should help performance and stability:

- Integration of RS RID state into the blacklisting framework.  This should hopefully greatly diminish long running jobs.
- Standardized handling of CLI args paths and taking arguments from stdin.
- Better sanity checking for LIO path names
- Sanity checking for missing INI sections.  It now prints a message to stderr and exits making it easier to debug config issues
- It now returns the last section or key found matching the request instead of the first.  You can still iterate over all sections and keys to get everything.  This makes it more natural when overriding included sections from other files.
- lio_cp does the write thing now when copying a directory to an new directory.
- Fix some lingering ZMQ bugs found after dropping CZMQ.  You can now use hostnames! instead of just IPs.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
What tests can we do to verify it all works 👌🏻
-- 
It's dark in this basement.

**Comment by tacketar** [comment]
Trust me:)

Actually that was one of the things I was going to discuss with you on 
the call today but you didn't attend:(  I have an idea to do some higher 
level testing to catch odd lio_* behavior vs the standard Linux 
command.  It's pretty easy to do and is useful for making sure POSIX 
behavior is being followed.  Still doesn't handle lower level testing.

**Comment by PerilousApricot** [comment]
Sorry. I slept in this morning :/ Comcast guy is here fixing my internet
(the cable to the pole got cut somehow). We can chat in like 20 mins if you
want. If the docker-ified LServer (@hellermf) is good to go, I could see
having jenkins do acceptance tests on master and if it works, push to a
"stable" branch in G

**Comment by PerilousApricot** [comment]
Committed in #169

**Pull request closed without merging**
