### PR TITLE
Make builds return correct error messages

### PR DESCRIPTION
**Pull request by PerilousApricot**
Ensure the error code propagates out of the script so jenkins knows
how to handle it

### CODE REVIEW

**Comment by PerilousApricot** [comment]
test this please

**Comment by tacketar** [comment]
What do you want me to do?  Just test that it builds and passes some 
sanity checks?

**Comment by PerilousApricot** [comment]
sorry, you dont have to do anything, it triggers jenkins to redo the build (see the "all checks have passed" bit in the web interface)

**Comment by tacketar** [comment]
Cool!

**Comment by PerilousApricot** [comment]
+1

**Comment by PerilousApricot** [comment]
:+1:

**Pull request merged**
