### PR TITLE
Add IBP server implementation

### PR DESCRIPTION
**Pull request by PerilousApricot**
Working on splitting Alan's giant branch into individual updates so they can be cleaned up. Initially going to 5483401e33c2f3b88b9581cd78b2034737c46e85

### CODE REVIEW

**Comment by PerilousApricot** [comment]
continued to 25aa5240ca4337873560c81188a362bf23f26621, which appears to be the end of the ibp_server changes.

**Comment by PerilousApricot** [comment]
@tacketar please put the correct license into this branch and rebase 0f81a83 with the changes.

**Comment by tacketar** [comment]
Oops!  Completely forgot about that.  Do you by chance have the script 
handy you used before?

**Comment by PerilousApricot** [comment]
I did a sed party :)

**Comment by PerilousApricot** [comment]
#moved to #153

**Pull request closed without merging**
