### PR TITLE
Bugfix/debian

### PR DESCRIPTION
**Pull request by hellermf**
Some Debian/Ubuntu packing fixes, mostly concerning the czmq package.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
You can drill down and split apart the parallel steps:

http://jenkins.accre.vanderbilt.edu/job/LStore-Pipeline/branch/bugfix%252Fdebian/2/flowGraphTable/

The plugin has an open issue to split it out better on the page.

**Comment by hellermf** [comment]
retest this please

**Comment by hellermf** [comment]
test this please

**Comment by PerilousApricot** [comment]
Jerasure shouldnt flap like that :(

## 

It's dark in this basement.

**Comment by PerilousApricot** [comment]
Do we still want to work on this, or has it been subsumed by the more recent PR?

**Comment by hellermf** [comment]
I think it should still be merged. I think the only thing holding us back was the Jerasure flapping on the Centos platforms which we have since diagnosed as the RPM .spec missing a line to trigger a ldconfig refresh which is external to these changes.

**Comment by hellermf** [comment]
...furthermore without this PR issue https://github.com/accre/lstore-release/issues/37 isn't really resolved cleanly.

**Comment by PerilousApricot** [comment]
Ah, gotcha. I think it needs to be rebased against the current master to be
mergeable

## 

It's dark in this basement.

**Comment by hellermf** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables  says that a JENKINS_URL environmental variable should be getting set however it appears this may not be the case. If I test ./debian/rules with "export JENKINS_URL=foo" it behaves as expected and disables czmq tests however in the real Jenkins environment this is not happening:

```

Tests enabled
...
   dh_auto_test
make[1]: Entering directory `/tmp/lstore-release/build/czmq/czmq/obj-x86_64-linux-gnu'
Running tests...
/usr/local/bin/ctest --force-new-ctest-process -j1
Test project /tmp/lstore-release/build/czmq/czmq/obj-x86_64-linux-gnu
    Start 1: czmq_selftest
1/1 Test #1: czmq_selftest ....................   Passed    9.84 sec


```

**Comment by PerilousApricot** [comment]
It's probably set foe the Jenkins job but not passing through to the docker
container inside

## 

It's dark in this basement.

**Comment by hellermf** [comment]
I'm certain you are right. I wasn't thinking about the entire system and the docker containers used.

**Comment by hellermf** [comment]
I think this is ready to be merged. Go ahead and do it if you agree.

**Comment by hellermf** [comment]
Also once merged we can close issue https://github.com/accre/lstore-release/issues/50

**Comment by PerilousApricot** [comment]
FWIW, if you write "Fixes #50" in the commit message, GH will close #50 automatically when it's merged.

**Comment by hellermf** [comment]
That is cool, I noticed that when I wrote "See #50" in a commit message GH automatically created a cross ref link. I'll start using the "Fixes #__" in my commit messages.

**Pull request merged**
