### PR TITLE
Base config pkg for use of Vanderbilt L-Store sys

### PR DESCRIPTION
**Pull request by hellermf**
Adds a package that provides a basic starting configuration for using the primary Vanderbilt L-Store system and a template for other configurations including running a local L-Server.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
I'm not a super fan of this. We should certainly have tools and base configs for people to use, but baking in the current configuration as a package seems off to me. Are we going to make new packages every time we need to change the configuration, then deploy the packages to all of the machines? That sounds like what configuration management is supposed to do.

**Comment by tacketar** [comment]
I'm definitely in favor of it but I wouldn't put it in lstore-release 
and I'd separate out the RID stuff.  I'd make a new lstore-sample-config 
package or some such and slap all the config files in there EXCEPT all 
the rid-*.cfg files.  Instead I'd just make a blank rid.cfg containing 
the file format.

You'd also need a helper script to sed the lserver IP addresses and the 
INI include paths.  This would provide the base for a fresh L-Store 
install with intelligent defaults which we sorely need.  I routinely 
setup new L-Servers and it's a PITA.  I don't care for it to be VU 
specific.  I'd like a generic package that would setup all the 
directories, install a base os_file structure, intelligent config, and 
/lfs_roots.   This package would assume lstore-release is installed 
already which is just binaries.  All that would be missing is the RID 
config.  We could add a few of the existing helper scripts to make that 
go quick.

This would greatly simplify setting up a completely fresh L-Store system.

Alan

**Comment by PerilousApricot** [comment]
I think we're shooting towards two separate things simultaneously and it's
a bit muddled:
- Distributing for others
- Speeding up rolling new servers/mounts out

Taking what you'd like to do, Alan, I suggest the following:
- in lio:
  - script to sed a config (this problem is almost certainly something done
    cleaner with the config parsing, but that can be for later)
  - add lfs_service_manager script
  - add a way to initialize OS directory (command line flag to server?
    Separate script?)
- Add "lstore" package with a dep to lstore-lio.
  -  Init script
  -  Sample fuse and server configs
    - Use standard Linux paths (logs in /var/log, etc..)
  - Logrotate stanzas
- Add "accre-lstore-config" package:
  - Create directories like /lio/log
  - Bring along different configs (if needed)
  - CMS-depot-probing script

## 

It's dark in this basement.

**Comment by PerilousApricot** [comment]
Or, some sort of "lfs_setup_config.sh" script could be provided, which
would automate the drudgery. Making directories, modifying a configuration,
and all that jazz wouldn't be hard to script up, if there was a clear
description of each step

## 

It's dark in this basement.

**Comment by hellermf** [comment]
I meant to do a little write up explaining my thoughts after creating the PR but got sidetracked. This is some stuff that I had held off on pushing upstream because I wasn't really satisfied with the state that it was in. However I finally decided that was worth pushing because it is pretty useful even in its current form (setting up clients and L-servers is no longer a PITA). Additionally I just wanted to get the conversation started by providing a straw-man implementation that can be attacked and morphed into a good general sample configuration.

Right now what I have muddles client and server configuration. It defaults to providing a working configuration for a client using the Vanderbilt L-Store system. The reconfig_lserver.sh script can be used to automatically generate a configuration for running a local LServer (basically just sed the IP address).

Things I would like to see:
- Separate client config from server config
- Make the configuration more generic yet still quick to get a working Vandy config
- Documentation
- Create a configuration wizard like script to generate a configuration, although enhancing config parsing with support for variables and such may make such scripting unnecessary
- initd/systemd/upstart service stop/start support for L-Server
- Log rotate for L-Server
- Generate osfile tree programmatically
- Generate rid config files programmatically

**Comment by hellermf** [comment]
I didn't see some of the comments until after I posted my most recent one, clearly we are all thinking many of the same things.

**Comment by tacketar** [comment]
Agreed.  -Alan

**Comment by PerilousApricot** [comment]
I'm gonna take a stab at doing what we discussed.

Matt - do you want to take a stab at making a "general" cpacklist for RPM
and DEB?

## 

It's dark in this basement.

**Comment by PerilousApricot** [comment]
Since this branch splits off a branch I rebased, I had to rebase this one as well. I didn't touch this one, I just made a new one (feature/toplevel-package) via cherry-picking commits.

**Comment by PerilousApricot** [comment]
superseded by #24

**Pull request closed without merging**
