### PR TITLE
Add meta-rpm to install lstore repository

### PR DESCRIPTION
**Pull request by PerilousApricot**

### CODE REVIEW

**Comment by PerilousApricot** [comment]
Haven't forgotten about this. I just need to sit down and rebase/tidy this branch before I smash it in.

**Comment by PerilousApricot** [comment]
@hellermf I rebased and removed the gpg key since it's not currently used anywhere. We should sign the repos, but until we actually figure out how we're going to do that, we should hold off on partial functionality. If that's okay with you, I'll push this on in.

**Comment by hellermf** [comment]
That is the gpg key that I have been using. As far as I can tell it does no harm including it. Even if it is ultimately just a placeholder for a future key it puts the pieces in place to support future features and helps me out. That said, yes it is okay with me to proceed with pushing this into 'master' with or without it.

**Comment by PerilousApricot** [comment]
Cool, I'll smash it in here in a sec. I couldn't find where it was actually used.

Once we get to signing everything, we'll almost certainly want to use GPG to perform the signing for each package, then inject that key into lstore-release instead of hard-coding it. To first order, the repos produced and signed individuals will be different than the repos produced, signed, and uploaded to http://www.accre.vanderbilt.edu/repos/lstore/ . We can sort out the details in a new branch and get it right all at once.

**Comment by PerilousApricot** [comment]
I guess to clarify, `gpg --armor --export --output "LSTORE-GPG-KEY"` could/should be added to the workflow to sync up the installed GPG key with what was actually used to sign everything.

**Comment by hellermf** [comment]
Yes although without the "--armor" on apt/deb platforms, I found out firsthand that the armored ASCII version does not work.

----- Original Message -----

**Comment by PerilousApricot** [comment]
Huh. Learn something new. I'd imagine that since the basement of apt is using GPG somewhere, it'd be able to accept the output from GPG....

**Pull request merged**
