### PR TITLE
Feature/deb packaging

### PR DESCRIPTION
**Pull request by hellermf**
Add support for building packages for deb packagebased linux distros

### CODE REVIEW

**Comment by PerilousApricot** [comment]
It appears to work with ubuntu-trusty. Kicking off a test with debian-jessie gives:

```
++ cp -ra /tmp/source/source/czmq/ ./
++ pushd czmq
++ dpkg-buildpackage -uc -us
/tmp/lstore-release/build/czmq/czmq /tmp/lstore-release/build/czmq /tmp/lstore-release/build
dpkg-buildpackage: source package czmq
dpkg-buildpackage: source version 3.0.2-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by unknown <build@unknown>
 dpkg-source --before-build czmq
dpkg-buildpackage: host architecture amd64
 debian/rules clean
dh clean 
   dh_testdir
   dh_auto_clean
   dh_clean
 dpkg-source -b czmq
dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision
dpkg-buildpackage: error: dpkg-source -b czmq gave error exit status 255
```

**Comment by hellermf** [comment]
Just to follow up did the change of version string from 3.0.2-1 to 3.0.2 in lstore-czmq fix this issue in debian-jessie?

**Comment by PerilousApricot** [comment]
I'm away from my machine (Titans game), but to test it I did "mkdir
scripts/docker/base/debian-jessie ; build-docker-base.sh ; package.sh"

## 

It's dark in this basement.

**Comment by PerilousApricot** [comment]
Back to you, @hellermf.

**Comment by hellermf** [comment]
Does that mean everything looks good to you? Should I do the merge?

**Comment by PerilousApricot** [comment]
I'll smash and rebase it. Just wanted to check with you that it doesn't
break anything on your side

## 

It's dark in this basement.

**Comment by hellermf** [comment]
It looks good to me.

**Comment by PerilousApricot** [comment]
Done.

**Pull request merged**
